[package]
name = "ch01-derive"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }

[[bin]]
name = "first"
path = "bin/first.rs"

[[bin]]
name = "second"
path = "bin/second.rs"

[[bin]]
name = "third"
path = "bin/third.rs"
