[package]
name = "bevy_model"
version = "0.1.0"
edition = "2024"

[dependencies]
arc-swap = "1.7.1"
bevy_ecs = "0.16.1"
colored = "3.0.0"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
dashmap = { version = "6.1.0" }
env_logger = "0.11.8"
log = "0.4.27"
